vimode: % searches for first suitable character
techee/geany-plugins pull request #1
Opened 2018-04-21 03:59 UTC by pcworld

`:help %` specifies:
> Find the next item in this line after or under the cursor and jump to
> its match.

2018-04-21 20:23 UTC, techee requested changes
Great! I haven't even announced the plugin and there's a first contributor! Thanks for the patch, I bet there will be tons of minor semantic issues like this one.

2018-04-21 20:23 UTC, techee commented on vimode/src/cmds/motion.c
> +	while (pos < p->line_end_pos) {
Please use the same indentation style (i.e. move { to a separate line). The same below.

2018-04-21 20:23 UTC, techee commented on vimode/src/cmds/motion.c
> +		if ((matching_pos = SSM(p->sci, SCI_BRACEMATCH, pos, 0)) != -1) {
I'd prefer splitting this to

```
gint matching_pos = SSM(p->sci, SCI_BRACEMATCH, pos, 0));
if (matching_pos != -1)
```

2018-04-22 03:56 UTC, pcworld commented
Fixed it (for use with `git rebase -i --autosquash`).

I found your PR by accident and wanted to try it since I've thought in the past that Geany having a vim mode would be interesting. I've noticed some other minor semantic deviations, however some of them are not as easily fixed. Maybe I'll get to write up some of them sometime.

2018-04-25 13:20 UTC, techee approved these changes

2018-04-25 13:21 UTC, techee commented
Merged, thanks!

2018-04-25 13:21 UTC, closed without merging